project_id: '516942'
api_token: 7429c231d264b80857311326382e54cb70807e90db2adf28cd3a831d514de0fee9f4fbc8f7f0d300
base_path: /Source Code
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: '/[0-2].txt'
    translation: /%two_letters_code%/%original_file_name%
